q-optimize/c3

c3/__init__.py
requirements.txt
setup.py

Fix tensorflow installation dependency on Windows. The current release has the following error:
```bash
pip install c3-toolset
.
.
.
tensorflow 2.3.1 requires gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
```
Closes #4
New `pip` resolution messes up dependencies for tensorflow.
Freeze version of `gast` to `0.3.3` to prevent conflicts.
Also made some minor fixes:
* Add `rich` to `requirements.txt`
* Fix the version number in `__init__.py`

Fix gast to resolve Tensorflow conflict

---

README.md

* Binder badge to launch notebooks in Binder
* Note on examples directory in Readme
* Note on Contributing doc in Readme to help newcomers

Update README with binder link and Contributing

---

CONTRIBUTING.md
c3/c3objs.py
c3/experiment.py
c3/generator/devices.py
c3/generator/generator.py
c3/libraries/fidelities.py
c3/optimizers/c3.py
c3/optimizers/optimizer.py
c3/optimizers/sensitivity.py
c3/parametermap.py
c3/system/chip.py
c3/system/model.py
c3/system/tasks.py
c3/utils/tf_utils.py
test/test_tf_utils.py

Making everything a `tf.Variable` caused performance problems. This reverts most instances back to `tf.constant`. Only optimization parameters are left as `tf.Variable`.

Replaced tf.Variable with tf.constant in most places.

---

.github/workflows/build_package.yml

Pin `qiskit` version in package build CI to fix issues with updated `numpy` compatibility.

Qiskit hotfix for Package Build CI

---

c3/qiskit/c3_backend.py
c3/qiskit/c3_backend_utils.py
test/conftest.py
test/test_qiskit.py

Added some minor qiskit fixes while working on QAOA implementation with our simulator
General improvements in code structure
* Update gateset for perfect simulator
* Added a get_labels utility function
* Cleaned up framework for physics simulator and add `TODO` where required
* Update tests to measure all qubits
* Include note about difference in qubit numbering in qiskit and C3
Further developments on qiskit integration (physics simulator, qaoa, OpenPulse etc) are currently suspended pending the completion of the following:
* Better naming scheme for gates, possibly adopting OpenQasm style `{"name": "u2", "qubits": [0], "params": [0.4,0.2]}`
* Parametric gates in perfect gates and physics unitaries
* Improvements on `evaluate()` and `process()` in `Experiment` class
* Virtual Z gates

Minor qiskit fixes

---

c3/qiskit/c3_backend.py
c3/qiskit/c3_backend_utils.py
test/test_qiskit.py

Closes #58 
Issues are bad, should fix
* Add new private variable `_flip_labels` in `C3QasmSimulator` which tracks whether qubit labels are to be flipped
* Add function `disable_flip_labels()` which disables the default behaviour to flip qubit state labels when generating experiment results in the qiskit-c3 interface
* Add `c3_backend_utils` function `flip_labels()` which flips state labels after experiment data is collected
* Updated tests to check for both qiskit style and original c3 style results in c3-qiskit experiment data
* Added notes in docstrings with details and links

Flip state labels to match Qiskit style basis vector ordering

---

.github/workflows/build_package.yml
.github/workflows/nightly_pypi.yml
.github/workflows/publish_pypi.yml
CONTRIBUTING.md
README.md
pytest.ini
requirements.txt

Faster and more robust CI checks
Time taken by test suite is gradually increasing. Cross-platform builds and dependencies require more nuanced testing.
* Speed up tests with multiprocessing. This is done with `pytest-xdist`
* The pip resolver differently handles `pip install -e .` and `pip install <package-name>`. As such, certain dependency resolution conflicts might crop up after release to `pip`. Added a CI that checks `pip` released packages install fine on all supported platforms - by directly installing from `pip`. This is a regression test for #5 and #4
* Stable Release to `pip` is now *only* possible when pushing to master with the version numbers duly updated
* Added note on nightly release to README.

Better Release and CI pipelines

---

.github/workflows/build_package.yml
.github/workflows/coverage.yml
.github/workflows/integration_test.yml
pytest.ini

Make parallel testing flexible for devs with and without `pytest-xdist`
Using `-nauto` in `pytest.ini` (as introduced in #62) would break tests for users without `pytest-xdist` installed and the error message is not particularly intuitive
* Remove `-nauto` from `pytest.ini`
* Add explicit `-n=auto` to CI workflows
If someone wants to parallelize their testing:
```bash
pip install pytest-xdist
pytest -vv test/ -n=auto
```
When creating a new development environment, `pytest-xdist` is included by default in the `requirements.txt`

Make parallel testing flexible

---

c3/generator/devices.py
c3/libraries/envelopes.py
c3/utils/utils.py

* Fix deprecation warnings with a decorator, usage `@deprecated("message")`
* Remove repeated variable initialisation
Going ahead, if we need more sophisticated deprecation handling, some useful resources are here:
* https://stackoverflow.com/questions/2536307/decorators-in-the-python-standard-lib-deprecated-specifically
* https://pypi.org/project/Deprecated/
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/deprecation.py

Deprecation decorator and minor code cleanups

---

.github/workflows/nightly_pypi.yml
.github/workflows/publish_pypi.yml

Python 2 is no longer available by default in apt repositories starting from Ubuntu 20.04
Unused `python-pip` in the release workflows is removed in this PR to fix breaking CD pipeline.

Hotfix: release pipeline

---

.github/workflows/build_package.yml
.github/workflows/coverage.yml
.github/workflows/integration_test.yml
c3/qiskit/c3_backend.py
c3/qiskit/c3_backend_utils.py
test/test_qiskit.py

Fail fast in testing and run slower tests after quicker tests
Fixes #77 
* Using `pytest` with the `-x` flag makes sure that testing will abort on the first failure. This has now been integrated into all the tests being run on the CI pipeline. For local testing, developers should add that flag when calling the `pytest` CLI
* We already mark some of our tests as `slow` based on expectations that these require more compute/time. The CI has now been modified to first run tests that are not marked as slow and only then run the slow tests (along with the fail fast described above). For local testing, developers should call `pytest` with the `-m "not slow"` flag to run the quicker tests first and can then run with the `-m "slow"` flag.

Efficient testing

---

.pre-commit-config.yaml
requirements.txt

Update `black` version in `pre-commit` hooks
Fix for https://github.com/psf/black/issues/1629 included in version [21.4b0](https://github.com/psf/black/releases/tag/21.4b0) and above
Bump `black` version in `.pre-commit-config.yaml`
Once this PR is merged, please perform the following steps to make sure your commit hooks and workflows use the latest black version:
`git stash push -m "WIP on <branch-name> <short status>"`
* `git checkout dev`
* `git pull upstream dev` assuming you are working in a forked repo
* `pip install --upgrade pip`
* `pip install --upgrade pre-commit`
* `git checkout <branch-name>`
* `git merge dev`
* `pre-commit install`
* `git stash pop`
* `git add <files>`
* `git commit -m <message>`
At this point, pre-commit hook should automatically update its dependencies to …

Update Black version in Pre-commit hooks

---

c3/libraries/algorithms.py
test/test_two_qubits.py

Update `tf_sgd` to use `maxiters` and include note on WIP TF Optimizers
Closes #102 and associates
- Add warnings to the `adam`, `adadelta` and `rmsprop` optimizers. These have incomplete/incorrect implementations while some of the default hyper-parameters have been altered without adequate reasoning or comments. Pending further investigations into these algorithms or without the option to alter these hyper-parameters from the user-space, these are essentially buggy and must be avoided. Also added `# TODO`s to make note of what needs to be done
- Updated the `tf_sgd` optimizer to use the correct `maxiters` parameter instead of `maxfun`. This is because these optimizers allow for directly controlling the number of algorithm iterations and not function evaluations.
- Added an Error Handling …

Fix API mismatch in Tensorflow Optimizers

---

docs/index.rst
docs/intro.rst

Add an introduction section to the online docs, continuing work on issue #17 
Newcomers find it difficult to grasp what the different parts of the codebase mean and how they interact with each other
Add sections explaining the following:
- The three building blocks:
- Device Model
- Classical Electronics
- Instructions
- Parameter Map
- Experiment
- Optimizer
- Libraries

Add Introduction to Documentation

---

test/conftest.py
test/test_qt_utils.py

Add tests for `utils/qt_utils.py`
Part of #92
Adds unit tests for some utility functions in qt_utils, which were not covered by tests yet. 
I tried to test the properties of the function's results as described in #71, so that the tests are independent of the function's implementation. For functions which can work with arbitrary dimensions (e.g. `xy_basis`), the test is repeated for some dimensions to be sure, e.g dim=3, 5, 10, 100. Going through all dimensions up to some max value would probably make the test run unnecessary long.

Add unit tests for qt_utils

---

c3/libraries/tasks.py
c3/model.py
test/test_model.cfg
test/test_model_spam.cfg
test/test_parsers.py

When a model is written to or read from a configuration file, the tasks are formatted and parsed, too.
Fixes #18 
Almost the same as it is done for the qubits and couplings in a model. There's a list of possible classes in `tasks.py:task_lib` and instances are created by passing the parsed dictionaries to the classes' constructors in the `params` argument. As far as I can see, adding that argument doesn't create any conflict with the normal usage of the constructors.

Read and write a model's tasks to config files

---

c3/optimizers/c2.py
test/c2.cfg
test/test_c2_calibration.py

Provide integration tests for c2 style calibration workflows
Fixes #118 
This provides an Integration Testing module for C2 style Optimization tasks. It checks for integration of the whole C2 calibration workflow with a mock function that mimics communication with a hardware. It also checks the integrity of the example `test/c2.cfg` config file. However this doesn't check if the optimization algorithms used (eg CMA-ES) are working as expected in minimizing the goal function. This is because the mock will return constant values.
We could have used monkeypatch type implementations or moved the mock_ORBIT to a fixture
However, unless the mock_ORBIT sees usage in other tests, it is left in this module.
This should provide ~100% coverage for `c3/optimizers/c2.py`
However, the overall project …

Integration Test for C2 style Calibration tasks

---

.github/workflows/build_package.yml
.github/workflows/integration_test.yml
.github/workflows/nightly_pypi.yml
.github/workflows/publish_pypi.yml
CONTRIBUTING.md
setup.py

This PR introduces tested support for Python 3.9
Closes #122 
We now test for Python 3.9 support on all 3 platforms in our CI. The same is also updated in the pypi package metadata to indicate Python 3.9 support during `pip installs`. This will be available immediately in the `nightly` release and become part of stable during the `1.3` minor release.

Provide support for Python 3.9

---

c3/libraries/algorithms.py
test/test_scan_algos.py
test/test_two_qubits.py

Add tests and cleanup algorithms library 
Total test coverage is getting affected by stale, unused, legacy code that is not (and need not be) tested. Additionally, presence of incorrect and incomplete implementations of algorithms might end up with erroneous results for 3rd party users.
- remove incomplete/incorrect adam, rmsprop, adadelta
- remove commented code blocks
- add test for lbfgs_grad_free
- add warnings for untested algos
- add test for sweep
- add test for grid2D 
Expected to increase the test coverage of `c3/libraries/algorithms.py` to 50%+
Please include and complete the following checklist. Your Pull Request is (in most cases) not ready for review until the following have been completed. You can create a draft PR while you are still completing the checklist. Check the …

Cleanup Algorithms Library

---

CHANGELOG.md
c3/qiskit/c3_backend.py
test/test_qiskit.py

Allows for serialisation of results from `c3.qiskit` simulator 
Closes #127 
- Convert `shots_data` to python list after rounding the `np.ndarray`
- Added regression tests to ensure results are always serialisable
Add notes on possible known quirks/drawbacks of this solution. If this introduces an API-breaking change, please provide an explanation on why it is necessary to break API compatibility and how users should update their notebook/script workflows once this PR is merged.
Please include and complete the following checklist. Your Pull Request is (in most cases) not ready for review until the following have been completed. You can create a draft PR while you are still completing the checklist. Check the [Contribution Guidelines](https://github.com/q-optimize/c3/blob/dev/CONTRIBUTING.m …

Qiskit serialise

---

docs/Parametermap.rst

Hotfix added missing doc page version of the ParameterMap Tutorial Jupyter.

Tutorial for pmap in docs

---

.github/workflows/build_package.yml
.github/workflows/nightly_pypi.yml
.github/workflows/publish_pypi.yml
CHANGELOG.md
CONTRIBUTING.md
setup.py

Drop Support for Python 3.6 
Closes #155
Stop running tests and publishing releases for Python 3.6
It should still be possible to install and use `c3-toolset` with Python 3.6 if one explicitly installs `tensorflow<=2.6` and `tensorflow-probability<=0.14` and then installs `c3-toolset`. However, going forward, we no longer officially support or test our builds in Python 3.6 or lower.
Please include and complete the following checklist. Your Pull Request is (in most cases) not ready for review until the following have been completed. You can create a draft PR while you are still completing the checklist. Check the [Contribution Guidelines](https://github.com/q-optimize/c3/blob/dev/CONTRIBUTING.md) for more details. You can mark an item as complete with the `- [x]` prefix

Drop support for Python 3.6
